//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FooService.ConsoleClient.Foo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Foo.IFooService")]
    public interface IFooService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFooService/ServiceAction", ReplyAction="http://tempuri.org/IFooService/ServiceActionResponse")]
        string ServiceAction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFooService/ServiceAction", ReplyAction="http://tempuri.org/IFooService/ServiceActionResponse")]
        System.Threading.Tasks.Task<string> ServiceActionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFooServiceChannel : FooService.ConsoleClient.Foo.IFooService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FooServiceClient : System.ServiceModel.ClientBase<FooService.ConsoleClient.Foo.IFooService>, FooService.ConsoleClient.Foo.IFooService {
        
        public FooServiceClient() {
        }
        
        public FooServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FooServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FooServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FooServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServiceAction() {
            return base.Channel.ServiceAction();
        }
        
        public System.Threading.Tasks.Task<string> ServiceActionAsync() {
            return base.Channel.ServiceActionAsync();
        }
    }
}
